default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_dev
  pool: 5
  username: devuser
  password: devuser100
  host: localhost
  port: 5432

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_live
  pool: 5
  username: devuser
  password: devuser100
  host: kimiyosi-db.clwtnwxrhpbf.us-east-2.rds.amazonaws.com
  port: 5432
